name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      CONNECTION_STRING_TEMPLATE: Server=tcp:127.0.0.1,1433;Database={0};User Id=sa;Password=VeryStrong!P@ssword111
    
    services:
      sql:        
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: VeryStrong!P@ssword111
          ACCEPT_EULA: Y          
        ports:
          - "1433:1433"

    steps:    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish OgcApi.Net.Features
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: OgcApi.Net.Features/OgcApi.Net.Features.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish OgcApi.Net.Features.SqlServer
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: OgcApi.Net.Features.SqlServer/OgcApi.Net.Features.SqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}